// <auto-generated />
using System;
using GamedayTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GamedayTracker.Data.Migrations
{
    [DbContext(typeof(BotDbContext))]
    [Migration("20260714072712_UpdateRelationship_Bank_GuildMember")]
    partial class UpdateRelationship_Bank_GuildMember
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GamedayTracker.Models.Bank", b =>
                {
                    b.Property<decimal>("BankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("DepositTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GuildMemberId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("LastDepositAmount")
                        .HasColumnType("numeric");

                    b.HasKey("BankId");

                    b.HasIndex("GuildMemberId")
                        .IsUnique();

                    b.ToTable("Bank");
                });

            modelBuilder.Entity("GamedayTracker.Models.Bet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("GameDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("GuildMemberMemberId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("Multiplier")
                        .HasColumnType("numeric");

                    b.Property<int>("Odds")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Payout")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("PlacedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Selection")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("WagerAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("GuildMemberMemberId");

                    b.ToTable("Bet");
                });

            modelBuilder.Entity("GamedayTracker.Models.Guild", b =>
                {
                    b.Property<decimal>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuildName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("GuildOwnerId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("IsDailyHeadlinesEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRealTimeScoresEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("NotificationChannelId")
                        .HasColumnType("text");

                    b.Property<bool>("ReceiveSystemMessages")
                        .HasColumnType("boolean");

                    b.HasKey("GuildId");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("GamedayTracker.Models.GuildMember", b =>
                {
                    b.Property<decimal>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("BetWins")
                        .HasColumnType("integer");

                    b.Property<string>("FavoriteTeam")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("GuildName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MemberName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("MemberId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("GamedayTracker.Models.PoolPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Balance")
                        .HasColumnType("double precision");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("DepositTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("GuildMemberId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("GuildMemberMemberId")
                        .HasColumnType("numeric(20,0)");

                    b.PrimitiveCollection<string[]>("Picks")
                        .HasColumnType("text[]");

                    b.Property<decimal>("PlayerId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("GuildMemberMemberId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("GamedayTracker.Models.Tickets.Ticket", b =>
                {
                    b.Property<decimal>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("GuildMemberMemberId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<decimal>("ThreadId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("TicketId");

                    b.HasIndex("GuildMemberMemberId");

                    b.ToTable("Ticket");
                });

            modelBuilder.Entity("GamedayTracker.Models.Bank", b =>
                {
                    b.HasOne("GamedayTracker.Models.GuildMember", "GuildMember")
                        .WithOne("Bank")
                        .HasForeignKey("GamedayTracker.Models.Bank", "GuildMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildMember");
                });

            modelBuilder.Entity("GamedayTracker.Models.Bet", b =>
                {
                    b.HasOne("GamedayTracker.Models.GuildMember", null)
                        .WithMany("Bets")
                        .HasForeignKey("GuildMemberMemberId");
                });

            modelBuilder.Entity("GamedayTracker.Models.GuildMember", b =>
                {
                    b.OwnsMany("GamedayTracker.Models.DailyNumbers.DailyNumberPick", "DailyNumbers", b1 =>
                        {
                            b1.Property<decimal>("GuildMemberMemberId")
                                .HasColumnType("numeric(20,0)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("date");

                            b1.Property<decimal>("GuildId")
                                .HasColumnType("numeric(20,0)");

                            b1.PrimitiveCollection<int[]>("Numbers")
                                .IsRequired()
                                .HasColumnType("integer[]");

                            b1.Property<string>("PlayType")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTimeOffset>("Timestamp")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<decimal>("UserId")
                                .HasColumnType("numeric(20,0)");

                            b1.HasKey("GuildMemberMemberId", "Id");

                            b1.ToTable("DailyNumberPick");

                            b1.WithOwner()
                                .HasForeignKey("GuildMemberMemberId");
                        });

                    b.Navigation("DailyNumbers");
                });

            modelBuilder.Entity("GamedayTracker.Models.PoolPlayer", b =>
                {
                    b.HasOne("GamedayTracker.Models.GuildMember", "GuildMember")
                        .WithMany()
                        .HasForeignKey("GuildMemberMemberId");

                    b.Navigation("GuildMember");
                });

            modelBuilder.Entity("GamedayTracker.Models.Tickets.Ticket", b =>
                {
                    b.HasOne("GamedayTracker.Models.GuildMember", null)
                        .WithMany("Tickets")
                        .HasForeignKey("GuildMemberMemberId");
                });

            modelBuilder.Entity("GamedayTracker.Models.GuildMember", b =>
                {
                    b.Navigation("Bank");

                    b.Navigation("Bets");

                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
